# Generated by Django 5.1.3 on 2025-12-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_album_author_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(null=True, to='app.artist'),
        ),
    ]
