# Generated by Django 5.1.3 on 2025-09-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
            ],
            options={
                'ordering': ['-author', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('bitrate', models.IntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.album')),
                ('artist', models.ManyToManyField(to='app.artist')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
