# Generated by Django 5.1.3 on 2025-12-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, to='app.artist'),
        ),
    ]
